FinalProject/ProductMvc/Controllers/CategoryController.cs
using ProductMvc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductMvc.Controllers
{
    public class CategoryController : Controller
    {
        VinaEntity db = new VinaEntity();
        public ActionResult Index()
        {
            return View(db.Categorys);
        }
        #region Create
        [HttpGet]
        public ActionResult Create()
        {            
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "CategoryID")]Category model)
        {
            if (ModelState.IsValid)
            {
                db.Categorys.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }            
            return View(model);
        }
        #endregion
        #region Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {           
            return View(db.Categorys.Find(id));
        }

        [HttpPost]
        public ActionResult Edit(Category model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }           
            return View(model);
        }
        #endregion

        #region Delete
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var _Category = db.Categorys.Find(id);           
            _Category.Products.ToList().ForEach(m=>db.Products.Remove(m));
            db.Categorys.Remove(_Category);
            db.SaveChanges();
            return new EmptyResult();
        }
        #endregion
    }
}

FinalProject/ProductMvc/Controllers/ProductController.cs
using ProductMvc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductMvc.Controllers
{
    public class ProductController : Controller
    {
        VinaEntity db = new VinaEntity();
        #region Show Product
        public ActionResult Index()
        {
            return View(db.Categorys);
        }
        public ActionResult ProductId(int id)
        {
            return View(db.Products.Where(m => m.CategoryID == id));
        }
        public ActionResult Details(int id)
        {
            return View(db.Products.Find(id));
        }
        public ActionResult Top5Product()
        {
            return PartialView(db.Products.Take(5));
        }
        #endregion
        #region CRUD
         #region Create
        [HttpGet, Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categorys, "CategoryID", "CategoryName");
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "ProductID")]Product model)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(model);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = model.ProductID });
            }
            ViewBag.CategoryID = new SelectList(db.Categorys, "CategoryID", "CategoryName", model.CategoryID);
            return View(model);
        }
        #endregion

        #region Edit
        
        public ActionResult Edit(int id)
        {
            var product = db.Products.Find(id);
            ViewBag.CategoryID = new SelectList(db.Categorys, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }
        [HttpPost]
        public ActionResult Edit(Product model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = model.ProductID });
            }
            ViewBag.CategoryID = new SelectList(db.Categorys, "CategoryID", "CategoryName", model.CategoryID);
            return View(model);
        }
        #endregion
        #region Delete .Dùng Ajax
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return new EmptyResult();
        }
        #endregion
        #endregion

    }
}

FinalProject/ProductMvc/Controllers/ShoppingController.cs
using ProductMvc.Models;
using ProductMvc.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductMvc.Controllers
{
    public class ShoppingController : Controller
    {
        // Hiển thị danh sách đơn hàng
        VinaEntity db = new VinaEntity();
        public ActionResult Index()
        {
            return View(db.Orders);
        }
        #region Create Order
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "OrderID")]Order model)
        {
            var CartList = (List<CartVM>)Session["Cart"];
            var OrdetailsList = new List<OrderDetail>();
            CartList.ForEach(m =>
            {                
                var _Product = db.Products.Find(m.Product.ProductID);
                OrdetailsList.Add(new OrderDetail
                {
                    ProductID = _Product.ProductID,
                    Quantity = m.Quantity
                });
            });
            model.Active = false;
            // thêm danh sách OrderDetails
            model.OrderDetails = OrdetailsList;
            // Thêm bảng Order
            db.Orders.Add(model);
            db.SaveChanges();
            Session["Cart"] = null;
            return RedirectToAction("CreateSuccess");
        }
        public ActionResult CreateSuccess()
        {
            return View();
        }
        #endregion
        #region Details Order
        public ActionResult Details(int id)
        {
            return View(db.Orders.Find(id));
        }
        #endregion
        #region Delete Order
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var _Order = db.Orders.Find(id);
            _Order.OrderDetails.ToList().ForEach(m => db.OrderDetails.Remove(m));
            db.Orders.Remove(_Order);
            db.SaveChanges();
            return new EmptyResult();
        }
        #endregion

        #region ShoppingCart
        public ActionResult ShowCart()
        {
            return View();
        }
        public ActionResult AddToCart(int id)
        {
            var _Product = db.Products.Find(id);
            var CartList = new List<CartVM>();
            if (Session["Cart"] != null)
            {
                CartList = (List<CartVM>)Session["Cart"];
                var OldCart = CartList.Find(m => m.Product.ProductID ==id);
                if (OldCart != null)
                {
                    var NewCart = new CartVM { Product = _Product, Quantity = OldCart.Quantity + 1 };
                    CartList.Remove(OldCart);
                    CartList.Add(NewCart);
                }
                else
                {
                    CartList.Add(new CartVM { Product = _Product, Quantity = 1 });
                }
            }
            else
            {
                CartList.Add(new CartVM { Product = _Product, Quantity = 1 });
            }
            Session["Cart"] = CartList;
            return RedirectToAction("ShowCart");
        }
        public ActionResult RemoveCart(int id)
        {
            var CartList = (List<CartVM>)Session["Cart"];
            var _Cart = CartList.SingleOrDefault(m => m.Product.ProductID == id);
            CartList.Remove(_Cart);
            Session["Cart"] = CartList;
            return new EmptyResult();
        }
        #endregion
    }
}

FinalProject/ProductMvc/Views/Shared/FooterPartial.cshtml
<pre style="font-family:Arial; font-size:16px; font-weight:bold;">
Địa chỉ : Thủ Đức, TPHCM
Điện thoại : 0905412314
Email : trung@gmail.com
</pre>

FinalProject/ProductMvc/Views/Shared/HeaderPartial.cshtml
<img src="/Content/Image/System/nen.jpg" style="width:1320px; height:200px; margin:5px 2px;">
@*<div style="font-size:30px; font-weight:bold; margin:10px;">YUGIOH</div>*@ 

FinalProject/ProductMvc/Views/Shared/LogOnPartial.cshtml
@{if (Request.IsAuthenticated)
  {
    <div style="border: 1px solid #bfbdbd; margin: 10px; padding: 10px;">
        @Html.ActionLink("Trang Quản Trị", "Index", "Account", null, new { @class = "linkButton1" })
        @Html.ActionLink("Thoát", "LogOff", "Account", null, new { @class = "linkButton1" })
        @Html.ActionLink("Đổi mật khẩu", "ChangePass", "Account", null, new { @class = "linkButton1" })
    </div> 
  }
  else
  {
    <div style="border: 1px solid #bfbdbd; margin: 10px; padding: 10px;">
        <a href="@Url.Action("ShowCart", "Shopping")" class="linkButton1">Giỏ Hàng Của Bạn</a>
    </div> 
  } 
}

FinalProject/ProductMvc/Views/Shared/MenuAdminPartial.cshtml
@Html.ActionLink("Trang Chủ","Index","Product")
@Html.ActionLink("Quản Lý Loại Sản Phẩm","Index","Category")
@Html.ActionLink("Quản lý Đơn Hàng","Index","Shopping")

FinalProject/ProductMvc/Views/Shared/MenuPartial.cshtml
<a href="@Url.Action("Index","Product")">Trang Chủ</a>
<a href="http://localhost:3436/Product/ProductId/1">Card bán lẻ</a>
<a href="http://localhost:3436/Product/ProductId/2">Nguyên bộ</a>
<a href="http://localhost:3436/Product/ProductId/3">Sản phẩm khác</a>
<a href="http://localhost:3436/Account/Logon">Đăng nhập</a>
<a href="http://localhost:3436/Account/Create">Đăng ký tài khoản</a>

FinalProject/ProductMvc/Views/Shared/SidebarPartial.cshtml
<div class="header1">
    Sản Phẩm Nổi Bật
</div>
<ul>
    <li><a href="#">Sản Phẩm Nổi bật 1</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 2 </a></li>
    <li><a href="#">Sản Phẩm Nổi bật 3</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 4</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 5</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 6 </a></li>
    <li><a href="#">Sản Phẩm Nổi bật 7</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 8</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 9</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 10</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 11</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 12</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 13</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 14</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 15</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 16</a></li>
    <li><a href="#">Sản Phẩm Nổi bật 17</a></li>
</ul>

FinalProject/ProductMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - NGUYEN VAN TRUNG </title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div>@Html.Partial("HeaderPartial")</div>
        <div class="float-right">
            @Html.Partial("LogOnPartial")
        </div>
        <nav class="mainMenu clear-both">@Html.Partial("MenuPartial")</nav>
    </header>
    <div class="body">
        <article class="inline-block main">
            @RenderBody()
        </article>
        <aside class="inline-block sidebar">
            @Html.Action("Top5Product", "Product")
        </aside>
    </div>
    <footer>
        @Html.Partial("FooterPartial")
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

</body>
</html>

FinalProject/ProductMvc/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - NGUYEN VAN TRUNG </title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div>@Html.Partial("HeaderPartial")</div>
        <div class="float-right">
            @Html.Partial("LogOnPartial")
        </div>
        <nav class="mainMenu clear-both">@Html.Partial("MenuAdminPartial")</nav>
    </header>
    <div class="body">
         @RenderBody()
    </div>
    <footer>
        @Html.Partial("FooterPartial")
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>